import type { ReleaseFeedItem, UserListeningStats } from "@/lib/types";

const kindColor = { OFFICIAL: "bg-lime text-black", LEAK: "bg-fuchsia-400 text-black", SNIPPET: "bg-sky-300 text-black", PRERELEASE: "bg-orange-300 text-black" };
export function Dashboard({ stats, releases }: { stats: UserListeningStats | null; releases: ReleaseFeedItem[] }) {
  const maxAlbumMinutes = Math.max(...(stats?.albumBreakdown.map((item) => item.minutes) ?? [1]));
  return <main className="min-h-screen bg-ink"><section className="grid-fade border-b border-white/10"><div className="mx-auto max-w-6xl px-6 py-20"><p className="mb-5 text-xs font-bold tracking-[.25em] text-lime">DON TOLIVER HQ / LISTENER INTELLIGENCE</p><h1 className="max-w-3xl text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-8xl">Run it up.<br/><span className="text-lime">Track it all.</span></h1><p className="mt-8 max-w-lg text-base leading-7 text-white/60">A private dashboard for every Don Toliver replay, plus a living signal feed for releases, snippets and underground discoveries.</p></div></section>
  <section className="mx-auto grid max-w-6xl gap-5 px-6 py-10 md:grid-cols-3"><Metric label="Minutes listened" value={stats?.totalMinutes?.toLocaleString() ?? "—"} note="from Spotify recent plays"/><Metric label="Unique Don tracks" value={stats?.uniqueTracks?.toString() ?? "—"} note="in your recent history"/><Metric label="Listener rank" value={stats?.percentile ? `Top ${stats.percentile}%` : "Sync to rank"} note="compared with active listeners"/></section>
  <section className="mx-auto grid max-w-6xl gap-10 px-6 pb-20 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-lime">YOUR ROTATION</p><h2 className="mt-1 text-2xl font-bold">Top tracks</h2></div><span className="text-xs text-white/40">Last Spotify sync</span></div><div className="space-y-2">{stats?.topTracks.length ? stats.topTracks.map((track, index) => <div className="flex items-center gap-4 rounded-xl bg-panel p-3" key={track.id}><span className="w-5 text-sm text-white/35">0{index + 1}</span>{track.artworkUrl ? <img src={track.artworkUrl} alt="" className="h-11 w-11 rounded-md object-cover"/> : <div className="h-11 w-11 rounded-md bg-white/10"/>}<div className="min-w-0 flex-1"><p className="truncate font-semibold">{track.title}</p><p className="truncate text-sm text-white/45">{track.album}</p></div><p className="text-sm text-lime">{track.plays} plays</p></div>) : <Empty text="Connect Spotify to see your Don Toliver rotation."/>}</div><h2 className="mb-4 mt-10 text-2xl font-bold">Album energy</h2>{stats?.albumBreakdown.map((album) => <div key={album.album} className="mb-4"><div className="mb-2 flex justify-between text-sm"><span>{album.album}</span><span className="text-white/45">{album.minutes} min</span></div><div className="h-2 overflow-hidden rounded bg-white/10"><div className="h-full rounded bg-lime" style={{ width: `${Math.max(4, album.minutes / maxAlbumMinutes * 100)}%` }}/></div></div>)}</div>
  <div><p className="text-xs font-bold tracking-[.18em] text-lime">LIVE SIGNAL</p><h2 className="mb-5 mt-1 text-2xl font-bold">New & discovered</h2><div className="space-y-3">{releases.length ? releases.map((release) => <a target="_blank" rel="noreferrer" href={release.sourceUrl} className="block rounded-xl border border-white/10 bg-panel p-4 transition hover:border-lime/60" key={release.id}><div className="flex gap-3">{release.imageUrl ? <img src={release.imageUrl} alt="" className="h-12 w-12 rounded-md object-cover"/> : <div className="h-12 w-12 rounded-md bg-white/10"/>}<div className="min-w-0 flex-1"><div className="mb-2 flex items-center justify-between gap-2"><span className={`rounded px-2 py-1 text-[10px] font-black ${kindColor[release.kind]}`}>{release.kind}</span><span className="text-[10px] tracking-wider text-white/40">{release.source}</span></div><p className="truncate font-semibold">{release.title}</p><p className="mt-1 text-xs text-white/45">Detected {new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(release.detectedAt))}</p></div></div></a>) : <Empty text="The discovery feed will populate when the scheduled poll first runs."/>}</div></div></section></main>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="rounded-2xl border border-white/10 bg-panel p-6 shadow-glow"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/45">{label}</p><p className="mt-4 text-3xl font-black tracking-tight text-lime">{value}</p><p className="mt-2 text-xs text-white/40">{note}</p></article>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-7 text-sm text-white/45">{text}</div>; }
